### ISSUE TITLE
Get similar syntax to other cloudyr packages

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#13]
Hi @leeper , I'd like to make it the same syntax as much as possible with the other packages, is there a list we can compile or point to to help with it?

One thing I note with the AWS packages is consistent storage of keys in environment arguments, that I can do at the very least - but is there anything else? We can start a list here.

**Comment by leeper** [comment]
I think environment variables are the main thing. Two other things I can think of:

1. Maybe take a look at the S3 (in the R sense of S3) object classes I'm using for buckets, so that the objects returned here look similar to what comes back from aws.s3.
2. You could try to mimic the higher-level functions I've added to aws.s3, such as `s3save()`, `s3load()`, `s3source()` etc. that provide AWS-backed versions of commonly used file functions. Might be nice to have the same style of functions here, like `gcs_save()`, `gcs_load()`, etc.

**Comment by MarkEdmondson1234** [comment]
Cool, I have literally just added `gcs_save() ` and `gcs_load()` :D `gcs_source()` will also be a great addition.  Will look at adding them and look at S3 for the next release.

**Comment by MarkEdmondson1234** [comment]
Environment variables are in:

```r
Sys.setenv("GCS_CLIENT_ID" = "mykey",
           "GCS_CLIENT_SECRET" = "mysecretkey",
           "GCS_WEB_CLIENT_ID" = "my-shiny-key",
           "GCS_WEB_CLIENT_SECRET" = "my-shiny-secret-key",
           "GCS_DEFAULT_BUCKET" = "my-default-bucket")
```

**Comment by MarkEdmondson1234** [comment]
All in now

**Comment by leeper** [comment]
Nice!
