### ISSUE TITLE
Use env-var GOOGLE_APPLICATION_CREDENTIALS or auth of gargle package

### ISSUE THREAD

**Issue by Pit-Storm** [cloudyr/googleCloudStorageR#131]
Hi @MarkEdmondson1234 ,

Thanks for your work and that great package!

Do you thought about switching the name of the ENV-VAR to the Google default on named `GOOGLE_APPLICATION_CREDENTIALS` ? Like [gaggle is doing it](https://gargle.r-lib.org/reference/credentials_app_default.html).? Or even using the Auth method provided by gaggle?

This would be a more convenient way to do Authentication and one has no need to set to variables pointing to the same location. Although deployment in GCP is very streamlined, because gaggle is discovering default application credentials for its self. So one doen't have to provide a json-key into the code.

Let me know if you need more information with this :-)

**Comment by MarkEdmondson1234** [comment]
I think it should work as its using `gargle` under the hood, but would like some example code to check it. e.g. call `token <- gargle::credentials_app_default()` with correct scopes and then maybe load token via `gcs_auth(token)` 

If I see some example of that working will look to integrate it more so it looks for it on startup.

**Comment by Pit-Storm** [comment]
The snippet you gave is not working.

As it is pointed out in [gcs_auth() docs](http://code.markedmondson.me/googleCloudStorageR/reference/gcs_auth.html) the auth is looking for a path to a json file. The discovery that gargle makes is, as far as i can understand it, not implemented in googleClaudStorageR.

Gargle has a [article about non-interactive auth](https://gargle.r-lib.org/articles/non-interactive-auth.html) and even a one [about using gargle in client packages](https://cran.r-project.org/web/packages/gargle/vignettes/gargle-auth-in-client-package.html).

The UseCase I'm adressing ist to deploy R code to GCP infrastructure where Application Default Credentials without a keyfile are used.
As far as I see it, there is an [issue for extending the application default credentials](https://github.com/r-lib/gargle/issues/78) discovery in gargle.

How can we work this out for this package here?

**Comment by bhelm-prosper** [comment]
Hi @MarkEdmondson1234 and @Pit-Storm,

I ran across a similar (if not the same) issue today, and ended up here.  My use case is running R on a Google Compute Engine instance (in JupyterLab).  I wanted to be able to use the credentials baked into the instance, instead of having to create and manage a JSON key myself.  

In this scenario the following line of your snippet returns NULL because there is no GOOGLE_APPLICATION_CREDENTIALS environment variable set pointing to a credential JSON.
`
token <- gargle::credentials_app_default()
`

However, as a workaround I found that using the GCE specific method for loading a token works fine:
`
library(googleCloudStorageR)
token <- gargle::credentials_gce()
gcs_auth(token=token)
gcs_list_objects("my_bucket")
`

I have found that in many client libraries the auth function goes through a waterfall that includes checking the env var, GCE default, manually specified credentials, etc.  That might be worth considering if you are looking to extend out-of-the-box functionality.

**Comment by Pit-Storm** [comment]
@bhelm-prosper I think this is the workaround I had been looking forward to. Did you install the package from cran or github?

**Comment by bhelm-prosper** [comment]
I hope it works for you!  I just used CRAN.

**Comment by MarkEdmondson1234** [comment]
Ahh I missed you were on a VM or similar in a GCP project.  In that case it makes sense `credentials_gce()` will do it.
