### ISSUE TITLE
Re auth travis?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#70]
Hi @leeper I see no commits to Travis appearing for this project, is there some setup that needs to be done after the auth token change? https://codecov.io/gh/cloudyr/googleCloudStorageR/commits

**Comment by leeper** [comment]
Just looked into this. Added a new encrypted token, so builds are being sent to the drat (see https://github.com/cloudyr/cloudyr.github.io/commit/73d38e7579b904b50c8b8979187e5118e9239793).

Looks like [code coverage is failing on Travis](https://travis-ci.org/cloudyr/googleCloudStorageR/builds/236947342#L963-L987), though. I'm not sure why that is since I've never seen an error emerge at that stage. Maybe @jimhester can help?

**Comment by MarkEdmondson1234** [comment]
Thanks!  I just tried it again myself to see if it was my fork, for some reason the tests complete in the check but when covr reruns them it fails...;(

```
> library("googleCloudStorageR")

Setting scopes to https://www.googleapis.com/auth/devstorage.full_control

If you need additional scopes set do so via options(googleAuthR.scopes.selected = c('scope1', 'scope2')) before loading library and include one required scope.

Warning message:

In mapply(FUN = f, ..., SIMPLIFY = FALSE) :

  longer argument not a multiple of length of shorter

> 

> test_check("googleCloudStorageR")
```
